PROJECT_NAME ?= aldesa-buildtrack
CI ?= false
FORCE_DESTROY ?= false
TF_DESTROY_AUTO_APPROVE ?= $(if $(filter true,$(CI)),-auto-approve,)

ENV ?= dev

BOOTSTRAP_COMPONENT := 00-bootstrap
BOOTSTRAP_DIR := terraform/envs/$(ENV)/$(BOOTSTRAP_COMPONENT)
BOOTSTRAP_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-bootstrap.tfplan
BOOTSTRAP_KMS_KEY_RING_NAME ?= kr-$(PROJECT_NAME)-$(ENV)-sops
BOOTSTRAP_KMS_CRYPTO_KEY_NAME ?= ck-$(PROJECT_NAME)-$(ENV)-sops

FOUNDATION_COMPONENT := 10-foundation
FOUNDATION_DIR := terraform/envs/$(ENV)/$(FOUNDATION_COMPONENT)
FOUNDATION_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-foundation.tfplan
FOUNDATION_BACKEND_PREFIX ?= $(ENV)/$(FOUNDATION_COMPONENT)

STORAGE_BQ_COMPONENT := 20-storage-bq
STORAGE_BQ_DIR := terraform/envs/$(ENV)/$(STORAGE_BQ_COMPONENT)
STORAGE_BQ_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-storage-bq.tfplan
STORAGE_BQ_BACKEND_PREFIX ?= $(ENV)/$(STORAGE_BQ_COMPONENT)
STORAGE_BQ_APPLY_PARALLELISM ?= 1

ORCHESTRATION_COMPONENT := 30-orchestration
ORCHESTRATION_DIR := terraform/envs/$(ENV)/$(ORCHESTRATION_COMPONENT)
ORCHESTRATION_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-orchestration.tfplan
ORCHESTRATION_BACKEND_PREFIX ?= $(ENV)/$(ORCHESTRATION_COMPONENT)
DAGS_SYNC_SOURCE_DIR ?= dags
DAGS_SYNC_DEST_PREFIX ?= dags
DAGS_SYNC_BUCKET ?=
DAGS_SYNC_DRY_RUN ?= false

GOVERNANCE_COMPONENT := 40-governance
GOVERNANCE_DIR := terraform/envs/$(ENV)/$(GOVERNANCE_COMPONENT)
GOVERNANCE_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-governance.tfplan
GOVERNANCE_BACKEND_PREFIX ?= $(ENV)/$(GOVERNANCE_COMPONENT)

BI_COMPONENT := 50-bi
BI_DIR := terraform/envs/$(ENV)/$(BI_COMPONENT)
BI_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-bi.tfplan
BI_BACKEND_PREFIX ?= $(ENV)/$(BI_COMPONENT)

CICD_COMPONENT := 60-cicd
CICD_DIR := terraform/envs/$(ENV)/$(CICD_COMPONENT)
CICD_PLAN_FILE ?= $(PROJECT_NAME)-$(ENV)-cicd.tfplan
CICD_BACKEND_PREFIX ?= $(ENV)/$(CICD_COMPONENT)

GCP_REGION ?= europe-west1
GCP_PROJECT_DEV ?= data-buildtrack-dev
GCP_PROJECT_PRO ?= data-buildtrack-pro

ifeq ($(ENV),dev)
SELECTED_PROJECT := $(GCP_PROJECT_DEV)
else ifeq ($(ENV),pro)
SELECTED_PROJECT := $(GCP_PROJECT_PRO)
else
$(error ENV must be one of: dev, pro)
endif

GOOGLE_PROJECT ?= $(SELECTED_PROJECT)
TF_SA_ACCOUNT_ID ?= sa-terraform-buildtrack
TF_SA_EMAIL ?= $(TF_SA_ACCOUNT_ID)@$(GOOGLE_PROJECT).iam.gserviceaccount.com
TF_SA_KEY_FILE ?=

ifneq ($(filter %-$(ENV),$(GOOGLE_PROJECT)),)
TFSTATE_ENV_TOKEN :=
else
TFSTATE_ENV_TOKEN := -$(ENV)
endif

TFSTATE_BACKEND_BUCKET_DEFAULT ?= $(GOOGLE_PROJECT)$(TFSTATE_ENV_TOKEN)-tfstate-$(GCP_REGION)
TFSTATE_BACKEND_BUCKET ?= $(TFSTATE_BACKEND_BUCKET_DEFAULT)
GOOGLE_ACCOUNT ?= $(shell command -v gcloud >/dev/null 2>&1 && gcloud config get-value account 2>/dev/null || true)

export GOOGLE_PROJECT

ifeq ($(CI),true)
ifneq ($(strip $(TF_SA_KEY_FILE)),)
export GOOGLE_APPLICATION_CREDENTIALS := $(TF_SA_KEY_FILE)
endif
else
ifndef GOOGLE_IMPERSONATE_SERVICE_ACCOUNT
export GOOGLE_IMPERSONATE_SERVICE_ACCOUNT := $(TF_SA_EMAIL)
endif
ifndef GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT
export GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT := $(TF_SA_EMAIL)
endif
endif
