.PHONY: help show_context
help: ## This help
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "\033[36m%-34s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

show_context: ## Print selected environment, project and Terraform path
	@echo "ENV=$(ENV)"
	@echo "CI=$(CI)"
	@echo "GOOGLE_PROJECT=$(GOOGLE_PROJECT)"
	@echo "GCP_REGION=$(GCP_REGION)"
	@echo "FORCE_DESTROY=$(FORCE_DESTROY)"
	@echo "TF_SA_ACCOUNT_ID=$(TF_SA_ACCOUNT_ID)"
	@echo "TF_SA_EMAIL=$(TF_SA_EMAIL)"
	@echo "TF_SA_KEY_FILE=$(TF_SA_KEY_FILE)"
	@echo "GOOGLE_IMPERSONATE_SERVICE_ACCOUNT=$${GOOGLE_IMPERSONATE_SERVICE_ACCOUNT:-<unset>}"
	@echo "GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT=$${GOOGLE_BACKEND_IMPERSONATE_SERVICE_ACCOUNT:-<unset>}"
	@echo "GOOGLE_APPLICATION_CREDENTIALS=$${GOOGLE_APPLICATION_CREDENTIALS:-<unset>}"
	@echo "BOOTSTRAP_DIR=$(BOOTSTRAP_DIR)"
	@echo "FOUNDATION_DIR=$(FOUNDATION_DIR)"
	@echo "FOUNDATION_BACKEND_PREFIX=$(FOUNDATION_BACKEND_PREFIX)"
	@echo "STORAGE_BQ_DIR=$(STORAGE_BQ_DIR)"
	@echo "STORAGE_BQ_BACKEND_PREFIX=$(STORAGE_BQ_BACKEND_PREFIX)"
